# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tmctl < Formula
  desc "tmctl"
  homepage "https://github.com/triggermesh/tmctl"
  version "1.1.2"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/triggermesh/tmctl/releases/download/v1.1.2/tmctl_macOS_amd64.tar.gz"
      sha256 "664694be1f08c6ebe978f8651b3e7842658864eea4ab140811b5fdc687606b0f"

      def install
        bin.install "tmctl"
        generate_completions_from_executable(bin/"tmctl", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/triggermesh/tmctl/releases/download/v1.1.2/tmctl_macOS_arm64.tar.gz"
      sha256 "ff81ed9cdac475e0ed4907567287b77ca9bfa15a85a8d17b42f41ea529a84c83"

      def install
        bin.install "tmctl"
        generate_completions_from_executable(bin/"tmctl", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/triggermesh/tmctl/releases/download/v1.1.2/tmctl_linux_arm64.tar.gz"
      sha256 "8ae190ecbc558eb2884f227f2ea08c3e1d6183c0508459554f0eb72d02f8b44f"

      def install
        bin.install "tmctl"
        generate_completions_from_executable(bin/"tmctl", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/triggermesh/tmctl/releases/download/v1.1.2/tmctl_linux_amd64.tar.gz"
      sha256 "b777f3054f23a7d4fa97949f2030cf360ea72bfe6a56bfd991f069e6b6c8488a"

      def install
        bin.install "tmctl"
        generate_completions_from_executable(bin/"tmctl", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/triggermesh/tmctl/releases/download/v1.1.2/tmctl_linux_armv6.tar.gz"
      sha256 "cccb35c7c0cd1f101737579146bf15000a1d49f14cd825f364d73966e13b9c76"

      def install
        bin.install "tmctl"
        generate_completions_from_executable(bin/"tmctl", "completion", shells: [:bash, :zsh])
      end
    end
  end
end
